// src/audit/enums/audit-action.enum.ts

export enum AuditAction {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  REGISTER_REQUEST = 'REGISTER_REQUEST',
  REGISTER_CREATED = 'REGISTER_CREATED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  LOGOUT = 'LOGOUT',
  REFRESH = 'REFRESH',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  USER_DELETED = 'USER_DELETED',
  ADDRESS_DELETED = 'ADDRESS_DELETED',
  ADDRESS_CREATED = 'ADDRESS_CREATED',
  ADDRESS_UPDATED = 'ADDRESS_UPDATED',
}
